package com.chrisworks.personal.inventorysystem.Backend.Entities.ENUM;

public enum APPLICATION_EVENTS {

    SALE_EVENT,

    DEBT_CLEARANCE_EVENT,

    WAREHOUSE_STOCK_UP_EVENT,

    SHOP_STOCK_UP_EVENT,

    RESTOCK_EVENT,

    WARE_BILL_REQUEST_EVENT,

    WARE_BILL_ISSUED_AND_SHIPPED_EVENT,

    WARE_BILL_RECEIVED_EVENT,

    SELLING_PRICE_CHANGED_EVENT,

    INCOME_CREATE_EVENT,

    INCOME_UPDATE_EVENT,

    EXPENSE_CREATE_EVENT,

    EXPENSE_UPDATE_EVENT,

    RETURN_SALE_EVENT
}
